#!/bin/bash

# Automated /etc/hosts Configuration for Gupii Development
# Safely adds required domain entries for local development

set -e

# Color codes for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

echo -e "${BLUE}🔧 Adding Gupii Development Domains to /etc/hosts${NC}"
echo "=================================================="

# Check if running as root/sudo
if [ "$EUID" -ne 0 ]; then
    echo -e "${RED}❌ This script requires sudo privileges${NC}"
    echo "Please run: sudo bash $0"
    exit 1
fi

# Define the domains to add
DOMAINS=(
    "gupii.local"
    "grafana.gupii.local"
    "prometheus.gupii.local"
    "sonar.gupii.local"
    "pgadmin.gupii.local"
    "mail.gupii.local"
    "minio.gupii.local"
    "jaeger.gupii.local"
)

HOSTS_FILE="/etc/hosts"
BACKUP_FILE="/etc/hosts.backup.$(date +%Y%m%d_%H%M%S)"

# Create backup
echo "📄 Creating backup of /etc/hosts..."
cp "$HOSTS_FILE" "$BACKUP_FILE"
echo -e "${GREEN}✅ Backup created: $BACKUP_FILE${NC}"

# Check if entries already exist
EXISTING_ENTRIES=()
for domain in "${DOMAINS[@]}"; do
    if grep -q "$domain" "$HOSTS_FILE"; then
        EXISTING_ENTRIES+=("$domain")
    fi
done

if [ ${#EXISTING_ENTRIES[@]} -gt 0 ]; then
    echo -e "${YELLOW}⚠️  Some entries already exist: ${EXISTING_ENTRIES[*]}${NC}"
    echo "Continuing with remaining entries..."
fi

# Add Gupii section marker
GUPII_MARKER="# Gupii Development Environment"
if ! grep -q "$GUPII_MARKER" "$HOSTS_FILE"; then
    echo "" >> "$HOSTS_FILE"
    echo "$GUPII_MARKER" >> "$HOSTS_FILE"
    echo "# Generated by Gupii setup script on $(date)" >> "$HOSTS_FILE"
fi

# Add each domain that doesn't already exist
ADDED_DOMAINS=()
for domain in "${DOMAINS[@]}"; do
    if ! grep -q "$domain" "$HOSTS_FILE"; then
        echo "127.0.0.1 $domain" >> "$HOSTS_FILE"
        ADDED_DOMAINS+=("$domain")
        echo -e "${GREEN}+ Added: $domain${NC}"
    else
        echo -e "${YELLOW}- Exists: $domain${NC}"
    fi
done

# Add end marker
if [ ${#ADDED_DOMAINS[@]} -gt 0 ]; then
    echo "# End Gupii Development Environment" >> "$HOSTS_FILE"
fi

echo ""
echo -e "${GREEN}✅ /etc/hosts configuration complete!${NC}"

if [ ${#ADDED_DOMAINS[@]} -gt 0 ]; then
    echo -e "${BLUE}📝 Added ${#ADDED_DOMAINS[@]} domain(s):${NC}"
    for domain in "${ADDED_DOMAINS[@]}"; do
        echo "  • $domain"
    done
else
    echo -e "${YELLOW}📝 All domains were already configured${NC}"
fi

echo ""
echo -e "${BLUE}🔍 Testing DNS resolution:${NC}"
for domain in "${DOMAINS[@]}"; do
    if ping -c 1 -W 1 "$domain" >/dev/null 2>&1; then
        echo -e "${GREEN}✅ $domain resolves correctly${NC}"
    else
        echo -e "${RED}❌ $domain resolution failed${NC}"
    fi
done

echo ""
echo -e "${GREEN}🚀 Ready for Gupii development!${NC}"
echo "You can now start the development environment."
echo ""
echo -e "${YELLOW}💡 To remove these entries later:${NC}"
echo "sudo nano /etc/hosts"
echo "Remove lines between '$GUPII_MARKER' markers"
echo ""